name: Development CI/CD
on:
  push:
    branches: [ development ]
jobs:
  integration-tests:
    name: DEV - Integration tests
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/integration-test.yml@main
    with:
      ENVIRONMENT: test
    secrets: inherit
  build:
    name: DEV - Application build
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/arm-build-to-ecr.yml@main
    with:
      ENVIRONMENT: development
    secrets: inherit
  run-migrations:
    name: DEV - Run migrations
    needs: build
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/run-container-on-ec2.yml@main
    secrets: inherit
    with:
      ENVIRONMENT: development
      IMAGE_TAG: ${{ github.sha }}
      APP_TYPE: prisma_migration
  deploy-app:
    name: DEV - Application deployment
    needs: run-migrations
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/run-container-on-ec2.yml@main
    secrets: inherit
    with:
      ENVIRONMENT: development
      IMAGE_TAG: ${{ github.sha }}
      APP_TYPE: node_app
  deploy-prisma:
    name: DEV - Deploy prisma studio
    needs: deploy-app
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/run-container-on-ec2.yml@main
    secrets: inherit
    with:
      ENVIRONMENT: development
      IMAGE_TAG: ${{ github.sha }}
      APP_TYPE: prisma_app
