name: Pull Requests CI/CD
on:
  [ pull_request ]
jobs:
  lint-check:
    name: PR - Linting verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Linting
        uses: meta-wto-test-org/fran-demo-devops/.github/actions/node-linting@main
        with:
          node-version: '18'
  integration-tests:
    name: PR - Integration tests
    uses: meta-wto-test-org/fran-demo-devops/.github/workflows/integration-test.yml@main
    needs: lint-check
    with:
      ENVIRONMENT: test
    secrets: inherit
